version: "3"
services:

  clienthandler:
    build:
      dockerfile: containers/clienthandler/Dockerfile
      context: .
    restart: always
    ports:
      - "${PROXYPORT}:${PROXYPORT}"
    environment:
      USER: ${AUTODNS_USER}
      PASSWORD: ${AUTODNS_PASSWORD}
      RESTURL: ${RESTURL}
      CONTEXT: ${AUTODNS_CONTEXT}
      PROXYPORT: ${PROXYPORT}
      PROXY_PROCESS_COUNT: ${PROXY_PROCESS_COUNT}

  redis:
    build: containers/redis
    restart: always
    ports:
      - "6379:6379"

  ws-gatehandler:
    build:
      dockerfile: containers/ws-gatehandler/Dockerfile
      context: .
    restart: always
    environment:
      USER: ${AUTODNS_USER}
      PASSWORD: ${AUTODNS_PASSWORD}
      CONTEXT: ${AUTODNS_CONTEXT}
      WS_GATE_URL: ${WS_GATE_URL}